### ISSUE TITLE
The running configurations in the paper

### ISSUE THREAD

**Issue by CNDOTA** [AnujMahajanOxf/MAVEN#1]
Hello,

Thanks for your codes. I'm running the codes with noisemix_smac.yaml in algs and sc2.yaml in envs.

However, it is hard to reproduce the MAVEN's results in the corridor and 6h_vs_8z.

Could you please provide the running configurations of MAVEN in your paper.

Thanks!

**Comment by CNDOTA** [comment]
Currently I use noisemix_episode.yaml. The parameter of rnn_discrim is set as False.

Is there any mismatch?

# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "parallel"
batch_size_run: 1

buffer_size: 5000
# pc mode buffer_size: 500

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "noise_q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
skip_connections: False
hyper_initialization_nonzeros: 0

mac: "noise_mac"
agent: "noise_rnn"
noise_dim: 2

mi_loss: 1
rnn_discrim: False  # currently adding by dong

discrim_size: 32
discrim_layers: 1

name: "noisemix"

**Comment by CNDOTA** [comment]
Currently, I use noisemix_episode.yaml. The parameter of rnn_discrim is set as False.

Is there any mismatch?


```
# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "parallel"
batch_size_run: 1

buffer_size: 5000
# pc mode buffer_size: 500

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "noise_q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
skip_connections: False
hyper_initialization_nonzeros: 0

mac: "noise_mac"
agent: "noise_rnn"
noise_dim: 2

mi_loss: 1
rnn_discrim: False  # currently adding by dong

discrim_size: 32
discrim_layers: 1

name: "noisemix"
```

**Comment by AnujMahajanOxf** [comment]
Hi, yes the current config files do not have the values for the grid search results in the camera ready. I have pushed the config keys for all the comparison plots in plot_keys folder. Regarding the rnn_discrim we do not see a significant change in performance between settings True and False. See the ablations discussion in the paper for more.

**Comment by GoingMyWay** [comment]
@CNDOTA 

Hi, have you figured out how to reproduce the result of the paper? I posted an issue on it: https://github.com/AnujMahajanOxf/MAVEN/issues/6
