### ISSUE TITLE
the code of 4step and 3step map

### ISSUE THREAD

**Issue by recordmp3** [AnujMahajanOxf/MAVEN#11]
May I know the code of environment "3step" and "4step" ? I only find map file here but I do not know the reward and environment configuration of both map in neither paper or code.

**Comment by jzzhang3** [comment]
also trying to re-create the 3step and 4step results here. anyone has new insights? '3step' and '4step' are not defined in the map registry. so we can't even run those maps.

**Comment by AnujMahajanOxf** [comment]
Hi, this should work now
