### ISSUE TITLE
Gradient error on noisemix

### ISSUE THREAD

**Issue by ludovic-carre** [AnujMahajanOxf/MAVEN#3]
I am trying to reproduce your results and I have an issue running the code (not running on a docker). The backpropagation fails with the following error:

```
[ERROR 13:59:02] pymarl Failed after 0:00:23!
Traceback (most recent calls WITHOUT Sacred internals):
  File "src/main.py", line 34, in my_main
    run(_run, _config, _log)
  File "/home/USER/.tmp/MAVEN/maven_code/src/run.py", line 48, in run
    run_sequential(args=args, logger=logger)
  File "/home/USER/.tmp/MAVEN/maven_code/src/run.py", line 181, in run_sequential
    learner.train(episode_sample, runner.t_env, episode)
  File "/home/USER/.tmp/MAVEN/maven_code/src/learners/noise_q_learner.py", line 168, in train
    loss.backward()
  File "/home/USER/.general_env/lib/python3.8/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/USER/.general_env/lib/python3.8/site-packages/torch/autograd/__init__.py", line 97, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [32, 56, 3, 9]], which is output 0 of SliceBackward, is at version 2; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

During handling of the above exception, another exception occurred:

Traceback (most recent calls WITHOUT Sacred internals):
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.8/subprocess.py", line 1079, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1796, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['tee', '-a', '/tmp/tmp8fr28bt_']' timed out after 1 seconds
```

I have spent some time searching for the error and came up with the following:

- In the noise QLearner, the latest version of PyMARL shows that the target_max_qvals should be computed from a detached version of mac_out in the train function, section "Max over target Q-Values"
- Here I am not sure at all, but computing q_softmax_actions with the detached mac_out removes the backprop error. However, I don't know if the MI loss is correctly backpropagated afterwards.

This is what I changed to have an up and running code, in the train function of src/learners/noise_q_learner.py:

```
        # Max over target Q-Values
        if self.args.double_q:
            mac_out_detach = mac_out.clone().detach()
            mac_out_detach[avail_actions == 0] = -9999999
            cur_max_actions = mac_out_detach[:, 1:].max(dim=3, keepdim=True)[1]
            target_max_qvals = torch.gather(
                target_mac_out, 3, cur_max_actions
            ).squeeze(3)
            # Get actions that maximise live Q (for double q-learning)
            #mac_out[avail_actions == 0] = -9999999
            #cur_max_actions = mac_out[:, 1:].max(dim=3, keepdim=True)[1]
            #target_max_qvals = th.gather(target_mac_out, 3, cur_max_actions).squeeze(3)
        else:
            target_max_qvals = target_mac_out.max(dim=3)[0]
```

```
        # Discriminator
        mac_out_detach = mac_out.clone().detach()
        mac_out_detach[avail_actions == 0] = -9999999
        q_softmax_actions = torch.nn.functional.softmax(
            mac_out_detach[:, :-1], dim=3
        )
        #mac_out[avail_actions == 0] = -9999999
        #q_softmax_actions = th.nn.functional.softmax(mac_out[:, :-1], dim=3)
```

Can you tell me if these changes are ok and if not how the gradient propagation should be fixed? I assume the proper way to fix the discriminator backprop problem would be to remove the part of the target that is in line with unavailable actions. I will keep looking for that in the code but I would really like to have your input.

**Comment by AnujMahajanOxf** [comment]
Hi, you should not use the latest PyMARL version for MAVEN as its not compatible. Use the source provided here.

**Comment by ludovic-carre** [comment]
I would like to adapt this MAVEN implementation to the latest PyMARL then. Can you give me a few directions to help me make the transition ? From what I have seen, not too much is different but maybe I missed something.

**Comment by ludovic-carre** [comment]
After investigation, the error comes from the torch version. Updates broke this code, when you mask out the unavailable actions, Torch loses the gradients while the Tensor is being tracked. What would be the best way to mask the unavailable actions without losing gradients ?
I believe the fix I provide in the first code snippet (target_max_qvals) works great since we are using mac_out to compute the target. We can clone the tensor and detach it to have appropriate targets.

I am really not sure about how to fix the q_softmax_actions though. Could I create a new tensor (cloning mac_out and masking it as a new input) or do we care about the preceding gradient flow ? I guess we do but I could really use your insight.

**Comment by ludovic-carre** [comment]
Last update, I have changed the hard mask on mac_out to a torch.where conditional tensor creation. From what I understand, this change should fix the last problem without losing gradient trace.
