### ISSUE TITLE
Help for the configuration of nstep_matrix game.

### ISSUE THREAD

**Issue by CNDOTA** [AnujMahajanOxf/MAVEN#4]
Hello,

Can you share MAVEN's .ymal file for the n_step matrix in the paper?

Some parameters are missing in the plot_keys/keys_matrix_games and I'm not sure my current setting is the same as yours.

Thank you very much!

**Comment by IouJenLiu** [comment]
I have similar issue. It would be great if you could share the script for reproducing the n_step matrix results reported in the paper. Thanks so much!

**Comment by AnujMahajanOxf** [comment]
Hi, I have uploaded the config file for nstep-matrix games [here](https://github.com/AnujMahajanOxf/MAVEN/blob/master/maven_code/plot_keys/nstep_matrix_noisemix_bandit.py). You can find the missing parameters there. Let me know if that helps!
